# Generated by Django 3.0.5 on 2021-06-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analizador_wifi', '0002_dispositivos_device_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dispositivos',
            old_name='osfamily',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='dispositivos',
            old_name='last_seen',
            new_name='hostname',
        ),
        migrations.RenameField(
            model_name='dispositivos',
            old_name='type',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='dispositivos',
            old_name='vendor',
            new_name='os_family',
        ),
        migrations.RenameField(
            model_name='dispositivos',
            old_name='os',
            new_name='os_system',
        ),
        migrations.RenameField(
            model_name='dispositivos',
            old_name='nombre_dispositivo',
            new_name='timestamp',
        ),
    ]
