# Generated by Django 3.0.5 on 2021-06-09 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modo_monitor', '0006_auto_20210609_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='ap',
            new_name='ap_id',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='mac_device',
            new_name='mac',
        ),
        migrations.AlterField(
            model_name='device',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
