# Generated by Django 3.0.5 on 2021-05-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analizador_wifi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivos',
            name='device_id',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
