# Generated by Django 3.2 on 2021-05-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='access_point',
            name='local_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
